### ISSUE TITLE
Order the CLI appointments by date/time

### ISSUE THREAD

**Issue by anseriformes** [lathamfell/AAAH#2]
Users would find it most helpful to view appointments ordered chronologically - first by date and second by time.

**Comment by tjsander** [comment]
Agreed -- this can be accomplished by sorting the array of inputs before
assigning 0..n indexes.

---
Travis J. Sanders
tjsander@gmail.com
+15038693797

**Comment by tjsander** [comment]
Feature implemented in main branch.
