### ISSUE TITLE
Automatic CLI refresh

### ISSUE THREAD

**Issue by anseriformes** [lathamfell/AAAH#3]
Is it possible to have the list refresh automatically after an appointment has been cancelled?

**Comment by tjsander** [comment]
I added a slight delay so that the filter would have time to update the
list after sending a cancellation email. Is it not long enough of a pause?

---
Travis J. Sanders
tjsander@gmail.com
+15038693797

**Comment by anseriformes** [comment]
Oh, no it's good. When I tested it first, it didn't refresh right away and with the instructions, it seemed like the user would be required to refresh the list manually. It's faster now.
